version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql:jdbc:postgresql://db:5432/queue_db
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      # Spotify OAuth environment variables
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SPOTIFY_CLIENT_ID=
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SPOTIFY_CLIENT_SECRET=
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SPOTIFY_REDIRECT_URI=
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPOTIFY_AUTHORIZATION_URI=https://accounts.spotify.com/authorize
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPOTIFY_TOKEN_URI=https://accounts.spotify.com/api/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPOTIFY_USER_INFO_URI=https://api.spotify.com/v1/me
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPOTIFY_USER_NAME_ATTRIBUTE=id
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SPOTIFY_SCOPE=streaming,playlist-modify-public,ugc-image-upload,user-read-email,user-read-private,user-read-currently-playing,user-read-recently-played,user-read-playback-state,user-modify-playback-state

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: queue_db
    ports:
      - "5432:5432"
